### ISSUE TITLE
[Question] Is this package suitable for deploying on other serverless infrastructure, like GCP Cloud Functions and Cloud Run?

### ISSUE THREAD

**Issue by steve-marmalade** [mirumee/lynara#1]
Hi team, I have been deploying my Ariadne application on GCP Cloud Run using `uvicorn` and it has worked reasonably well, although I often have suspected that the serverless nature of the runtime (unallocating CPU immediately after sending a response) might not be the perfect fit. Do you recommend using `lynara` when deploying on any serverless infrastructure, or is this package meant specifically to translate Lambda Events into HTTP Requests?

**Comment by pkucmus** [comment]
Good question and the short answer would be that there is no support for anything else than AWS Lambdas right now, but the only reason for that is that the matter was never explored. 

Depends on how a GCP Cloud function works (I don't have any experience with those) but I can't imagine it something drastically different than what AWS does, so with some modifications the Lynara Interface layer should be able to "translate" to ASGI - those are just thoughts though.

On a side note, if you don't need the ASGI layer with Ariadne you could use [Ariadne Lambda](https://ariadnegraphql.org/docs/aws-lambda) for a simpler setup, but then again it's also AWS oriented and changing that would entail more or less the same steps as for Lynara.

**Comment by pkucmus** [comment]
Did I answer the question?

**Comment by steve-marmalade** [comment]
Yes, thank you! I actually ended up deploying to a [GCP Managed Instance Group](https://cloud.google.com/compute/docs/instance-groups#managed_instance_groups) to avoid some of the challenges with serverless. :pray:
